name: CI

on: [ push, pull_request ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: "Run tests on Ubuntu"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update -qq -y && sudo apt-get install -qq -y wget curl shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: make test

  macos:
    runs-on: macos-latest
    name: "Run tests on macOS"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install wget shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: make test

  freebsd:
    runs-on: ubuntu-latest
    name: "Run tests on FreeBSD"
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      id: freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        copyback: false
        prepare: |
          pkg install -y wget curl shunit2
        run: |
          export SHUNIT2="$(command -v shunit2 2>/dev/null)"
          make test
